### ISSUE TITLE
mismatched types

### ISSUE THREAD

**Issue by tkburgett** [cubehub/rust-gpredict#1]
orbit_nr is initialized as u64 but then is set to a u32 later on the line 'self.sat.orbit_nr = self.p_sat.orbit;' which causes and error. Changing the initialization of orbit_nr to u32 seemed to fix the problem.

The file this all is in is /rust-gpredict-...../master/src/predict.rs

**Comment by andresv** [comment]
I will look into it in the evening.

**Comment by andresv** [comment]
Now it builds with 32 bit machine: https://github.com/cubehub/rust-gpredict/commit/4f262248f1cbf357f141e7ddde1a3557633cf0fa
